M48
; DRILL file {KiCad (6.0.6-0)} date 2022 November 04, Friday 12:46:31
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2022-11-04T12:46:31+01:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.0.6-0)
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0276
%
G90
G05
T1
X3.9445Y-3.7145
X3.9445Y-3.7815
X5.0552Y-3.7145
X5.0552Y-3.7815
T0
M30
